version: '3'

volumes: 
  data:

services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - data:/home/dynamodblocal/data
    ports:
     - "8042:8000"
