version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin!
    ports:
      - 27017:27017
    volumes:
      - ${HOME}/DockerProjects/nosql/mongodev/data:/data/db

  mongo_express:
    image: mongo-express
    container_name: mongoexpress
    depends_on: 
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin!
      ME_CONFIG_MONGODB_SERVER: mongodev
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin!
    restart: always
    ports:
      - 8081:8081


# volumes:
  # mongodb_data_container:


