version: '3.3'

services:
   db:
     image: mysql:latest
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin!
       MYSQL_DATABASE: dev
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin!
       
     volumes:
       - data:/var/lib/mysql
volumes:
	data: {}
